# Generated by Django 5.2.4 on 2025-08-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
